# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a570f485fb27c2a4d7e951d679ad3be534eecccbc1b877ebd0043701e580595b6183f735a25d0372bb3d6a570d3a69ce5993a1db946649fb185b0957c6efbc

test:
  secret_key_base: 35f418c9efbce47be21cd2354ad4013d2563bda875ef714a08b919c8c327b16a12f15a09143500ffde096d83c144e54e8bf3fae9b701c6e54e68aa5652a0fa5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
